# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
  - container: mta
    image: 'ghcr.io/sap/mbtci-java11-node14:latest'
    options: --user 0:0

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: Build MTA for SAP Business Technology Platform
  jobs:
    - job: build
      container: mta
      steps:
        - bash: 'mbt build -p=cf -t=mta_archives --mtar=din-cap.mtar'
        - publish: $(System.DefaultWorkingDirectory)/mta_archives
          artifact: MTA
